export const locations = [
  {id: 1, title: 'India', country: 'USA', selected: false},
  {id: 2, title: 'USA', country: 'India', selected: false},
  {id: 3, title: 'Japan', country: 'Japan', selected: false},
  {id: 4, title: 'Spain', country: 'Spain', selected: false},
  {id: 5, title: 'France', country: 'Spain', selected: false},
  {id: 6, title: 'Germany', country: 'Spain', selected: false},
  {id: 7, title: 'Italy', country: 'Spain', selected: false},
  {id: 8, title: 'Canada', country: 'France', selected: false},
  {id: 9, title: 'Australia', country: 'Germany', selected: false},
  {id: 10, title: 'China', country: 'Germany', selected: false},
  {id: 11, title: 'India', country: 'Germany', selected: false},
  {id: 12, title: 'India', country: 'Germany', selected: false},
  {id: 13, title: 'India', country: 'Germany', selected: false},
  {id: 14, title: 'India', country: 'Germany', selected: false},
  {id: 15, title: 'India', country: 'Germany', selected: false},
  {id: 16, title: 'India', country: 'Germany', selected: false},
  {id: 17, title: 'India', country: 'Germany', selected: false},
];
