export default {
  emptyName: 'Please enter Full Name',
  invalidName: 'Please enter valid Full Name',
  emptyUsername: 'Please enter User Name',
  invalidUsername: 'Please enter valid User Name',
  emptySurname: 'Please enter username',
  invalidSurname: 'Please enter valid Surname',
  emptAdreess: 'Please enter  Address ',
  invalidpostalAdreess: 'Please enter valid Postal Address',
  emptyMobile: 'Please enter Mobile Number',
  invalidMobile: 'Please enter valid Mobile Number',
  emptyEmail: 'Please enter  Email and Mobile Number',
  emptyUserEmail: 'Please enter Email',
  emptyUserPassword: 'Please enter Password',
  invalidEmail: 'Please enter valid Email',
  emptyPassword: 'Please enter  Password',
  emptyNewpassword: 'Please enter  New Password',
  emptyOldPassword: 'Please enter Old Password',
  invalidPassword: 'Please enter Password (Ex.Jhon@123)',
  invalidUserName: 'Please enter User Name (Ex.Jhon@123)',
  checkLoginPassword: 'Please enter Password',
  emptyConfirmPassword: 'Please enter Confirm Password',
  invalidConfirmPassword: 'Confirm Password should be same as the password',
  emptyAnnouce: 'Please enter title of your annouce',
  invalidAnnouce: 'Please enter valid title of your annouce',
  emptyremark: 'Please enter Remark',
  invalidRemark: 'Please enter valid Remark',
  emptyactiveBoxError: 'I accept Terms & conditions and Privacy Policy',
  emptyDescription: 'Please enter Description',
  emptyPrice: 'Please enter Price',
  passwordNotMatch: 'Password does not match with Confirm Password',
  emtyDistance: 'Please select Distance',
  emptyOtp: 'Please Enter OTP',
  invalidOtp: 'Please Enter Valid OTP',
  emptyIBAN: `Please Enter IBAN`,
  invalidIBAN: `Please Enter Valid IBAN`,
  emptyPostalcode: `Please Enter Postalcode`,
  invalidPostalcode: `Please Enter Valid Postalcode`,
  emptyCity: `Please Enter City.`,
  invalidCity: `Please Enter Valid City.`,
  emptyOwnerName: 'Please enter Owner Name.',
  invalidOwnerName: 'Please enter valid Owner Name.',
  emptyBillingAdreess: 'Please enter Billing Address. ',
  invalidBillingAddress: 'Please enter valid Billing Address.',
  emptySpecialPrecaution: 'Please enter SpecialPrecaution.',
  emptyWeekendPrice: 'Please enter Weekend Price.',
  emptyPriceperweek: 'Please enter Price Per Week.',
  emptyPhoneNumber: 'Please enter Phone Number.',
  invalidPhoneNumber: 'Please enter valid Phone number.',
  emptyLocation: 'Please enter Location',
  invalidLocation: 'Please enter valid  Location',
  emptyDeliveryCost: 'Please Delivery Cost.',
  emptyReportMessage: 'Please enter Message',
  emptyChatRenterMessage: 'Please enter Message',
  invalidPostalAddress: 'Please enter valid Postal Address',
  emptyOfferPrice: 'Please enter Price',
  emptyTitle: 'Please enter Title',
  emptyPerantID: 'Please enter Perant ID',
  invalidPerantID: 'Please enter only Number',
  emptyTag: 'Please enter Tag',
  emptyCreator: 'Please enter Creator',
  emptyTopic: 'Please enter Topic',
  emptySubTopic: 'Please enter Sub Topic',
  emptyCategory: 'Please select Category',
  emptySubCategory: 'Please select Sub Category',
  emptyPFP: 'Please select PFP',
  emptyImage: 'Please Upload Image',
  emptyDisplayImage: 'Please Upload Display Image',
  emptyCountryCode: 'Please select Country Code',
  emptySellIdeaType: 'Please select Sell Idea Type',
  emptyPostUplodPost: 'Please select Upload Post ',
  emptyMessage: 'Please enter Message',
  emptySubject: 'Please enter Subject',
  emptySelectIdea: 'Please select Idea',
  emptyStackAmount: 'Please enter Staked Amount',
  invalidStackAmount: 'Staked amount should be greater than',
};
