import color from '@theme/color';
import font from '@theme/font';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  headerContainerStyle: {
    paddingTop: 14,
    paddingBottom: 10,
    backgroundColor: color.primaryBG,
  },
  screenBackgroundContainerStyle: {
    backgroundColor: color.primaryBG,
  },
  container: {
    flex: 1,
    backgroundColor: color.primaryBG,
  },

  ContentContainers: {
    flex: 1,
  },
  ContentManageContainers: {
    flex: 1,
    marginTop: 26,
  },
  weekMainView: {
    height: 86,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 10,
    marginBottom: 26,
    paddingVertical: 10,
    borderRadius: 5,
    marginTop: 26,
  },
  weekMainShowSessionView: {
    height: 80,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 10,
    padding: 5,
    borderBottomWidth: 1,
    borderColor: color.buttonBG,
  },
  weekRemoveBorderSessionView: {
    height: 80,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 10,
    padding: 5,
  },
  weekTextStyle: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16.34,
    fontFamily: font.openSansRegular,
    marginBottom: 10,
    flex: 1,
    color: color.primaryText,
  },
  sessionNameInputStyle: {
    borderWidth: 0,
    backgroundColor: color.secondaryBG,
  },
  imageUploadContanier: {
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 10,
    paddingVertical: 20,
    alignItems: 'center',
    borderRadius: 5,
  },
  imageText: {
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 18,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
  },
  optionalTextStyle: {
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    fontWeight: '300',
  },
  imageUploadRowViewStyle: {
    flexDirection: 'row',
    marginTop: 10,
  },
  videoUploadContanier: {
    backgroundColor: color.secondaryBG,
    width: '100%',
    alignItems: 'center',
    borderRadius: 5,
    height: 116,
    justifyContent: 'center',
  },
  uploadTextRegular: {
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 10.7,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
    marginTop: 3,
  },
  weekRowViewManage: {
    flexDirection: 'row',
  },
  clipText: {
    fontSize: 14,
    lineHeight: 16,
    color: color.primary,
    fontFamily: font.workSansRegular,
  },
  clipContainer: {
    borderColor: color.primary,
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    marginLeft: 0,
  },
  exerciseView: {
    height: 120,
    backgroundColor: color.buttonBG,
    marginTop: 23,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseAddView: {
    height: 88,
    backgroundColor: color.buttonBG,
    marginTop: 22,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exerciseTextStyle: {
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 18,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
  },
  summaryViewStyle: {
    marginTop: 23,
    marginBottom: 25,
  },
  bottonView: {
    marginTop: 9,
    marginBottom: 32,
  },
  contentContainerStyle: {
    flexGrow: 1,
    marginTop: 23,
  },
  weekConditionTextStyle: {
    fontSize: 20,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    lineHeight: 23,
    fontWeight: '400',
  },
  blackViewMain: {
    height: 40,
    backgroundColor: color.secondaryBG,
    marginTop: 14,
    borderRadius: 5,
    flexDirection: 'row',
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  blackTextStyle: {
    lineHeight: 30,
    fontSize: 12,
    fontFamily: font.openSansRegular,
    marginLeft: 10,
    color: color.primaryText,
    flex: 1,
    fontWeight: '400',
  },
  hamburgIconStyle: {
    marginLeft: 10,
  },
  uploadVideoStyle: {
    height: 198,
    backgroundColor: color.buttonBG,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
  },
  uploadVideoText: {
    fontSize: 12,
    lineHeight: 14,
    color: color.secondaryText,
    fontWeight: '300',
    fontFamily: font.openSansRegular,
  },
  coachInstructionsViewStyle: {
    height: 136,
    backgroundColor: color.secondaryBG,
    marginTop: 9,
    paddingVertical: 5,
    paddingLeft: 10,
    paddingRight: 3,
    marginBottom: 6,
  },
  coachTitleStyle: {
    flex: 1,
    fontSize: 12,
    fontFamily: font.openSansRegular,
    lineHeight: 18,
    color: color.primaryText,
    fontWeight: '600',
  },
  rowView: {
    flexDirection: 'row',
  },
  wordTitleStyle: {
    fontSize: 10,
    fontFamily: font.openSansRegular,
    color: color.lightgray,
    fontWeight: '400',
  },
  inputTitleStyle: {
    fontSize: 10,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginTop: 5,
  },
  textTable: {
    fontSize: 12,
    lineHeight: 20,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    fontWeight: '400',
  },
  textTypeTable: {
    fontSize: 10,
    lineHeight: 20,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginLeft: 5,
    fontWeight: '400',
  },
  tableViewStyle: {
    height: 59,
    backgroundColor: color.primaryText,
    flexGrow: 1,
    paddingHorizontal: 5,
  },
  tableViewMStyle: {
    paddingHorizontal: 3,
    marginTop: 6,
  },
  tableTextStyle: {
    color: color.primaryText,
    marginHorizontal: 10,
    padding: 0,
    fontSize: 14,
    fontFamily: font.openSansRegular,
    textAlign: 'center',
    fontWeight: '400',
  },
  tableTextSecStyle: {
    backgroundColor: color.secondaryBG,
    marginBottom: 3,
    borderRadius: 2,
    color: color.primaryText,
    padding: 0,
    paddingLeft: 5,
    width: 83,
  },
  clipOpenTextStyle: {
    color: color.secondaryBG,
    fontSize: 14,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    lineHeight: 16,
  },
  clipAddNewTextStyle: {
    color: color.secondaryBG,
    fontSize: 14,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    lineHeight: 18,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  clipOpenStyle: {
    height: 30,
    borderRadius: 5,
    width: 175,
    backgroundColor: color.primary,
    alignItems: 'center',
    borderColor: color.primary,
    marginLeft: 0,
  },
  mainBorderStyle: {
    borderWidth: 1,
    borderColor: color.primary,
    marginTop: 32,
    paddingHorizontal: 10,
    borderRadius: 10,
    paddingBottom: 17,
  },
  borderStylePosition: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    zIndex: 1,
    top: -11,
    left: 10,
  },
  borderTitleStyle: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primary,
    backgroundColor: color.primaryBG,
    paddingHorizontal: 5,
    fontWeight: '700',
  },
  iconPositionChangeHandler: {
    justifyContent: 'flex-end',
    flex: 1,
    flexDirection: 'row',
  },
  iconManageColor: {
    backgroundColor: color.primaryBG,
    paddingHorizontal: 10,
  },
  marginStyleTop: {
    marginTop: 23,
  },
  newSessionViewStyle: {
    flexDirection: 'row',
    marginTop: 29,
    marginBottom: 23,
  },
  weekDayTextStyle: {
    fontSize: 16,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    flex: 1,
    fontWeight: '600',
  },
  clipSessionStyle: {
    borderRadius: 5,
    backgroundColor: color.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
  },
  sessionShowCardStyle: {
    height: 45,
    backgroundColor: color.secondaryBG,
    marginBottom: 10,
    borderRadius: 5,
    paddingHorizontal: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  sessionCardText: {
    fontSize: 16,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    flex: 1,
    fontWeight: '400',
  },
  showBottomCardStyle: {
    height: 45,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 25,
    alignItems: 'center',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: color.buttonBG,
  },
  showOptionBottom: {
    fontSize: 16,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginLeft: 6,
    fontWeight: '400',
  },
  sessionInputStyle: {
    marginBottom: 23,
    marginTop: 20,
  },
  cardSetsViewRowStyle: {
    height: 23,
    marginTop: 3,
    width: 79,
    backgroundColor: color.secondaryBG,
    borderRadius: 2,
    alignItems: 'center',
    flexDirection: 'row',
  },
  lineStyleInput: {
    height: 16,
    width: 1,
    backgroundColor: color.lightgray,
  },
});

export default styles;
