import color from '@theme/color';
import font from '@theme/font';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.primaryBG,
  },
  mainContainer: {
    marginTop: 35,
  },
  payoutView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nextPayoutView: {
    flex: 1,
    width: 167,
    height: 92,
    backgroundColor: color.primary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 20,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: color.lightgray,
  },
  nextTitleText: {
    fontSize: 14,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
    lineHeight: 19.07,
    color: color.secondaryBG,
  },
  nextAmountText: {
    marginTop: 10,
    fontSize: 25,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
    lineHeight: 34.05,
    color: color.secondaryBG,
  },
  lastPayoutView: {
    flex: 1,
    width: 166,
    height: 92,
    backgroundColor: color.secondaryBG,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  lastTitleText: {
    fontSize: 14,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
    lineHeight: 19,
    color: color.primaryText,
  },

  lastAmountText: {
    marginTop: 10,
    fontSize: 25,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
    lineHeight: 34.05,
    color: color.primaryText,
  },
  nextDateTitleText: {
    marginTop: 5,
    fontSize: 10,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    lineHeight: 13.62,
    color: color.secondaryBG,
  },
  lastDateTitleText: {
    flex: 1,
    marginLeft: 5,
    fontSize: 10,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    lineHeight: 13.62,
    color: color.primaryText,
  },
  nextDateText: {
    fontSize: 10,
    fontFamily: font.openSansRegular,
    fontWeight: '700',
    lineHeight: 13.62,
    color: color.secondaryBG,
  },
  lastDateText: {
    fontSize: 10,
    fontFamily: font.openSansRegular,
    fontWeight: '700',
    lineHeight: 13.62,
    color: color.primary,
  },
  progressView: {
    flex: 1,
    marginTop: 5,
    flexDirection: 'row',
  },
  connectBtnView: {
    marginTop: 2,
    backgroundColor: color.skyBlue,
    height: 131,
    borderRadius: 10,
    padding: 14,
  },
  btnTitleView: {
    flexDirection: 'row',
  },
  connectToPaypalText: {
    marginTop: 14,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 19.07,
    color: color.primaryText,
  },
  btnTitleText: {
    marginLeft: 12.05,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 21.79,
    color: color.midnightBlue,
  },
  paypalBtn: {
    marginTop: 19,
    height: 32,
    width: 185,
    borderRadius: 5,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: color.pacificBlue,
    flexDirection: 'row',
    alignItems: 'center',
  },
  paypalBtnText: {
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16.34,
    color: color.secondaryBG,
    marginLeft: 10,
  },
  transactionHeadingView: {
    marginTop: 21,
    flexDirection: 'row',
    alignItems: 'center',
  },
  transactionHeadingText: {
    flex: 1,
    fontFamily: font.workSansRegular,
    fontWeight: '500',
    fontSize: 17,
    lineHeight: 19.94,
  },
  filterBtn: {
    height: 36,
    width: 36,
    borderRadius: 3,
    backgroundColor: color.primaryText,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentContainerStyle: {
    marginTop: 26,
    flexGrow: 1,
    paddingBottom: 50,
  },
  chartLable: {
    width: 60,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 10.5,
    lineHeight: 14.3,
    top: -6,
    color: color.primaryText,
  },
});

export default styles;
