import color from '@theme/color';
import font from '@theme/font';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.primaryBG,
  },
  keyBoardView: {
    flex: 1,
    backgroundColor: color.primaryBG,
  },
  contentContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  inputContentContainers: {
    flex: 1,
    marginBottom: 50,
  },
  bgImageStyle: {height: 221, width: '100%'},
  viewUserStyle: {
    width: 129,
    height: 30,
    backgroundColor: color.secondaryBG,
    borderRadius: 24,
    marginTop: 15,
    alignSelf: 'flex-end',
    marginHorizontal: 15,
    borderWidth: 1,
    borderColor: color.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  VideoUserStyle: {
    width: 129,
    height: 30,
    backgroundColor: color.deepPurpleColor,
    borderRadius: 24,
    marginTop: 10,
    marginRight: 15,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  viewUserText: {
    fontSize: 13,
    fontFamily: font.workSansMedium,
    color: color.primary,
    marginRight: 10,
  },
  videoUserText: {
    fontSize: 13,
    fontFamily: font.workSansMedium,
    color: color.secondaryBG,
    flex: 1,
  },
  manageViewSpaceStyle: {
    justifyContent: 'space-between',
    flex: 1,
    flexDirection: 'row',
  },
  managePlayViewSpaceStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  VideoPositionViewShow: {
    height: 29,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    backgroundColor: color.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  VideoPositionTextShow: {
    color: color.secondaryBG,
    fontSize: 12,
    fontFamily: font.workSansMedium,
  },
  backStyle: {
    paddingLeft: 13,
    marginTop: 10,
  },
  likeRowViewManage: {
    flexDirection: 'row',
    marginTop: 10,
  },
  likeViewStyle: {
    marginRight: 12,
  },
  shareViewStyle: {
    marginRight: 20,
  },
  followerShowView: {
    flexDirection: 'row',
    marginBottom: 14,
    marginLeft: 20,
  },
  priceContainer: {
    borderRadius: 27,
    backgroundColor: color.secondaryBG,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 11,
    padding: 4,
    marginRight: 14,
    height: 19,
  },
  priceText: {
    fontFamily: font.openSansCondensedMedium,
    fontSize: 10,
    paddingRight: 4,
    color: color.primaryText,
    fontWeight: '600',
    lineHeight: 14,
    paddingLeft: 2,
  },
  platStyleView: {
    height: 60,
    backgroundColor: color.primary,
    paddingVertical: 13,
    paddingHorizontal: 20,
  },
  platStyleTitleText: {
    fontSize: 18,
    fontFamily: font.workSansMedium,
    color: color.secondaryBG,
  },
  platStyleDescriptionText: {
    fontSize: 12,
    fontFamily: font.workSansMedium,
    color: color.secondaryBG,
  },
  englishViewStyle: {
    height: 29,
    backgroundColor: color.deepPurpleColor,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    paddingHorizontal: 20,
    alignItems: 'center',
    flexDirection: 'row',
  },
  weekTextsStyle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    marginHorizontal: 5,
  },
  userCardViewStyle: {
    marginTop: 18,
    height: 59,
    backgroundColor: color.priceTagBG,
    borderRadius: 5,
    marginHorizontal: 20,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: color.priceTagBG,
  },
  userImageStyle: {height: 49, width: 49},
  userNameText: {
    fontSize: 15,
    fontFamily: font.openSansSemiBold,
    color: color.primaryText,
    marginBottom: 5,
  },
  userSubcribersText: {
    fontSize: 10,
    fontFamily: font.workSansRegular,
    color: color.primaryText,
  },
  userTextRowView: {flex: 1, marginLeft: 10},
  titleRowViewStyle: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 10,
  },
  fullTitle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
    marginLeft: 10,
  },
  horizontalStyle: {
    marginHorizontal: 20,
  },
  detailsTextStyle: {
    fontSize: 15,
    fontFamily: font.workSansMedium,
    marginTop: 26,
    marginBottom: 6,
    color: color.secondaryText,
  },
  decriptionTextStyle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
  },
  topContantFlatist: {marginHorizontal: 20},
  rowView: {
    marginHorizontal: 20,
    marginTop: 29,
    marginBottom: 23,
  },
  rowTextPicks: {
    fontSize: 15,
    fontFamily: font.workSansMedium,
    color: color.primaryText,
  },
  reviewsStyle: {
    fontFamily: font.workSansRegular,
    fontWeight: '500',
    marginTop: 28,
    fontSize: 16,
    lineHeight: 18,
    color: color.primaryText,
    marginHorizontal: 20,
  },
  ratingViewStyle: {
    fontFamily: font.openSansRegular,
    fontSize: 8,
    color: color.primaryText,
    textAlign: 'center',
    marginBottom: 21,
  },
  reviewRowView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  reviewTextStyle: {
    marginLeft: 7,
    fontSize: 12,
    fontFamily: font.openSansBold,
    color: color.primaryText,
  },
  ratingTextStyle: {
    marginLeft: 4,
    fontSize: 12,
    fontFamily: font.openSansMedium,
    color: color.primaryText,
  },
  contentContainerStyle: {
    flexGrow: 1,
    marginTop: 5,
  },
});

export default styles;
