// import color from '@theme/color';
// import font from '@theme/font';
// import {StyleSheet} from 'react-native';

// const styles = StyleSheet.create({
//   container: {
//     marginVertical: 20,
//   },
//   labelStyle: {
//     fontSize: 13,
//     fontFamily: font.openSansRegular,
//     fontWeight: '600',
//     color: color.black15,
//     backgroundColor: color.screenBackground,
//     zIndex: 1,
//     position: 'absolute',
//     paddingHorizontal: 5,
//     top: -7,
//     marginLeft: 7,
//   },
//   inputContainer: {
//     height: 46,
//     borderRadius: 5,
//     borderWidth: 1,
//     borderColor: color.borderGray,
//     flexDirection: 'row',
//     alignItems: 'center',
//     paddingHorizontal: 12,
//   },
//   inputStyle: {
//     flex: 1,
//   },
//   errorLabel: {
//     fontSize: 12,
//     lineHeight: 16,
//     color: color.errorRed,
//     fontFamily: font.openSansMedium,
//     marginTop: 50,
//     position: 'absolute',
//   },
//   calenderValue: {
//     fontSize: 12,
//     lineHeight: 16,
//     color: color.black15,
//     fontFamily: font.openSansRegular,
//     fontWeight: '400',
//   },
//   placeholder: {
//     fontSize: 12,
//     lineHeight: 15,
//     color: color.gray,
//     fontFamily: font.openSansRegular,
//     fontWeight: '400',
//   },
//   calenderContent: {
//     backgroundColor: color.white,
//     paddingTop: 5,
//     maxHeight: 402,
//     borderRadius: 12,
//     shadowColor: color.Gray48,
//     shadowOffset: {
//       width: 0,
//       height: 2,
//     },
//     shadowOpacity: 0.25,
//     shadowRadius: 3.84,
//     elevation: 5,
//   },
//   headerText: {
//     fontSize: 16,
//     lineHeight: 24,
//     color: color.black90,
//     fontFamily: font.openSansBold,
//   },
//   arrowContainer: {
//     height: 40,
//     width: 40,
//     borderRadius: 6,
//     borderWidth: 1,
//     borderColor: color.borderGray,
//     alignItems: 'center',
//     justifyContent: 'center',
//     backgroundColor: color.white,
//     shadowColor: color.droppedShadow,
//     shadowOffset: {
//       width: 0,
//       height: 1,
//     },
//     shadowOpacity: 0.1,
//     shadowRadius: 2.22,
//     elevation: 3,
//   },
//   todayDateContainer: {
//     height: 36,
//     borderRadius: 6,
//     backgroundColor: color.white,
//     marginVertical: 16,
//     marginHorizontal: 16,
//     alignItems: 'center',
//     justifyContent: 'center',
//     shadowColor: '#2A3B51',
//     shadowOffset: {
//       width: 0,
//       height: 1,
//     },
//     shadowOpacity: 1,
//     shadowRadius: 2, // Adjust this value as needed
//     elevation: 3,
//   },
//   dateValue: {
//     fontSize: 14,
//     lineHeight: 20,
//     color: color.extraLightGray,
//     fontFamily: font.openSansMedium,
//     fontWeight: '500',
//   },
//   dayStyle: {
//     alignItems: 'center',
//     justifyContent: 'center',
//     height: 30,
//     width: 30,
//   },
//   dayTextStyle: {
//     fontSize: 14,
//     fontFamily: font.openSansRegular,
//     lineHeight: 24,
//     color: color.extraLightGray,
//   },
//   headerTitle: {
//     fontFamily: font.openSansRegular,
//     fontWeight: '600',
//     fontSize: 16,
//     lineHeight: 24,
//     color: color.purple,
//     textAlign: 'center',
//     textDecorationLine: 'underline',
//     textDecorationStyle: 'solid',
//   },
//   yearView: {
//     flex: 1,
//     height: 34,
//     alignItems: 'flex-start',
//     marginBottom: 30,
//   },
//   yearText: {
//     fontFamily: font.openSansRegular,
//     fontWeight: '600',
//     fontSize: 14,
//     lineHeight: 24,
//     color: color.black,
//   },
// });
// export default styles;
