import color from '@theme/color';
import font from '@theme/font';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    backgroundColor: color.primaryBG,
    paddingHorizontal: 0,
  },
  inputContentContainers: {
    flex: 1,
    marginBottom: 20,
  },
  bgImageStyle: {
    height: 221,
    width: '100%',
    marginTop: 20,
  },
  viewUserStyle: {
    width: 129,
    height: 30,
    backgroundColor: color.secondaryBG,
    borderRadius: 24,
    marginTop: 15,
    alignSelf: 'flex-end',
    marginRight: 15,
    borderWidth: 1,
    borderColor: color.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  VideoUserStyle: {
    width: 129,
    height: 30,
    backgroundColor: color.primary,
    borderRadius: 24,
    marginTop: 15,
    alignSelf: 'flex-end',
    marginRight: 15,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    marginBottom: 15,
  },
  viewUserText: {
    fontSize: 13,
    fontFamily: font.openSansRegular,
    color: color.primary,
    marginRight: 10,
    fontWeight: '500',
  },
  videoUserText: {
    fontSize: 13,
    fontFamily: font.openSansRegular,
    color: color.secondaryBG,
    flex: 1,
    fontWeight: '500',
  },
  manageViewSpaceStyle: {
    justifyContent: 'space-between',
    flex: 1,
  },
  contentContainerStyle: {
    flexGrow: 1,
    marginTop: 16,
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  clipText: {
    fontSize: 11,
    color: color.primaryText,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
  },
  clipContainer: {
    borderColor: color.primary,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginLeft: 0,
    height: 30,
  },
  fullTitle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.secondaryText,
    marginLeft: 10,
    fontWeight: '400',
  },
  titleRowViewStyle: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 10,
  },
  horizontalStyle: {
    marginHorizontal: 20,
  },
  detailsTextStyle: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    marginTop: 26,
    marginBottom: 6,
    color: color.primaryText,
    fontWeight: '500',
    lineHeight: 18,
  },
  decriptionTextStyle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    fontWeight: '400',
    lineHeight: 16,
  },
  cardStyleLight: {
    height: 240,
    backgroundColor: color.paleLavender,
    marginTop: 20,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  priceStructureText: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    fontWeight: '500',
  },
  priceRadioEmptyText: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginLeft: 5,
    flex: 1,
    fontWeight: '400',
  },
  subscriptionRadioText: {
    fontSize: 15,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginLeft: 5,
    flex: 1,
    fontWeight: '500',
  },
  sessionNameInputStyle: {
    borderWidth: 0,
    backgroundColor: color.secondaryBG,
    marginBottom: 0,
    borderRadius: 5,
    height: 36,
  },
  centnerInputStyle: {
    fontFamily: font.openSansRegular,
    fontSize: 12,
    color: color.primaryText,
    fontWeight: '400',
  },
  containerStyles: {
    width: 166,
    marginRight: 0,
    marginBottom: 3,
  },
  styleRowInputManage: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonContainerStyles: {
    marginTop: 12,
    marginBottom: 26,
  },
  priceDecriptionText: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    marginTop: 16,
    fontWeight: '400',
  },
  weekMainShowSessionView: {
    height: 80,
    backgroundColor: color.secondaryBG,
    paddingHorizontal: 10,
    marginHorizontal: 20,
    padding: 5,
    borderBottomWidth: 0.5,
    borderColor: color.lightgray,
  },
  weekRowViewManage: {
    flexDirection: 'row',
  },
  weekTextStyle: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16.34,
    fontFamily: font.openSansRegular,
    marginBottom: 10,
    flex: 1,
    color: color.primaryText,
  },
  sessionRowViewStyle: {
    height: 48,
    width: '100%',
    borderColor: color.lightgray,
    borderBottomWidth: 0.5,
    paddingTop: 3,
  },
  sessionRowViewStyleBorderZero: {
    paddingTop: 3,
    height: 48,
  },
  decTextStyle: {
    fontSize: 14,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    fontWeight: '300',
  },
  repsTextStyle: {
    fontSize: 12,
    fontFamily: font.openSansRegular,
    color: color.primaryText,
    fontWeight: '600',
    marginTop: 5,
  },
  //** modal Style */
  modalContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 39,
  },
  modalStyle: {
    width: '100%',
    paddingHorizontal: 45,
    paddingTop: 40,
    backgroundColor: color.secondaryBG,
    alignItems: 'center',
    borderRadius: 10,
    shadowColor: color.primaryText,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  congratulationsTitle: {
    fontSize: 14,
    textAlign: 'center',
    color: color.primaryText,
    fontFamily: font.openSansRegular,
    marginTop: 12,
    marginBottom: 8,
    fontWeight: '600',
  },
  congratulationsDescriptionText: {
    fontSize: 12,
    textAlign: 'center',
    color: color.primaryText,
    fontFamily: font.openSansRegular,
    fontWeight: '400',
  },
  buttonStyleContent: {
    borderRadius: 6,
    width: 114,
    marginBottom: 29,
    marginTop: 47,
  },
  headerContainerStyle: {
    paddingTop: 17,
    paddingBottom: 8,
    paddingHorizontal: 20,
  },
  contentView: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 5,
  },
  flatListSessionStyle: {
    marginTop: 16,
  },
  CollapsibleCardContainerStyle: {
    marginHorizontal: 20,
  },
  CollapsibleContentStyle: {
    paddingHorizontal: 0,
    borderTopWidth: 0,
  },
});

export default styles;
