export default {
  splashVideo: require('./video/Splash_Video.mp4'),
  SplashBackground: require('./image/splashBackground.png'),
  bodiFyLogo: require('./image/bodiFyLogo.png'),
  instructorType: require('./image/instructorType.png'),
  trainerType: require('./image/trainerType.png'),
  frame: require('./image/cardfitnes.png'),
  shodowCard: require('./image/shodowCard.png'),
  user: require('./image/user.png'),
  sliderCard: require('./image/sliderCard.png'),
  greenCard: require('./image/greenCard.png'),
  star: require('./image/star.png'),
  marketPlace: require('./image/storefront.png'),
  calendar: require('./image/calendar_month.png'),
  programsBG: require('./image/programsBG.png'),
  programs: require('./image/programs.png'),
  deleteAccount: require('./image/deleteAccount.png'),
  logout: require('./image/logout.png'),
  emailConfirmation: require('./image/emailConfirmation.png'),
  myWorkoutCardLibrary: require('./image/myWorkoutCard.png'),
  videoShowCard: require('./image/videoShowCard.png'),
  profileImage: require('./image/profileImage.png'),
  userProfile: require('./image/userProfile.png'),
  workOutDetails: require('./image/workOutDetails.png'),
};
