import color from '@theme/color';
import font from '@theme/font';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  headerLableStyle: {
    fontFamily: font.workSansRegular,
    fontWeight: '500',
    fontSize: 20,
    lineHeight: 23,
    color: color.primaryText,
  },
  screenBackgroundContainerStyle: {
    backgroundColor: color.primaryBG,
  },
  headerContainerStyle: {
    paddingTop: 14,
    paddingBottom: 0,
    backgroundColor: color.primaryBG,
  },
  searchContainerStyle: {
    marginTop: 30,
    marginBottom: 0,
  },
  mainContainer: {
    flex: 1,
    backgroundColor: color.primaryBG,
  },
  contentContainer: {
    flexGrow: 1,
  },
  footerCom: {
    marginBottom: 30,
  },
  btnRowView: {
    marginVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnOutlineStyle: {
    flex: 1,
    height: 40,
    backgroundColor: color.primaryBG,
    borderWidth: 1,
    borderColor: color.primary,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
  },
  btnOutlineText: {
    marginLeft: 7,
    color: color.primary,
    fontFamily: font.openSansRegular,
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 18,
  },
  btnSolidStyle: {
    marginLeft: 15,
    flex: 1,
    height: 40,
    backgroundColor: color.primary,
    borderWidth: 1,
    borderColor: color.primary,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
  },
  btnSolidText: {
    marginLeft: 7,
    color: color.secondaryBG,
    fontFamily: font.openSansRegular,
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 18,
  },
  modalContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalInnerContainer: {
    width: 315,
    backgroundColor: color.secondaryBG,
    borderRadius: 10,
    paddingVertical: 20,
  },
  imageStyle: {
    alignSelf: 'center',
  },
  modalTitleText: {
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 19.07,
    color: color.primaryText,
  },
  modalDesText: {
    marginTop: 31,
    paddingHorizontal: 46,
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 19.07,
    color: color.primaryText,
  },
  modalEditTitleText: {
    marginTop: 29,
    paddingHorizontal: 21,
    textAlign: 'center',
    fontFamily: font.workSansRegular,
    fontSize: 14,
    lineHeight: 16.07,
    color: color.primaryText,
  },
  modalDescriptionText: {
    marginTop: 10,
    paddingHorizontal: 13,
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 19.07,
    color: color.primaryText,
  },
  modalDestTitleText: {
    marginTop: 31,
    paddingHorizontal: 46,
    textAlign: 'center',
    fontFamily: font.openSansRegular,
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 19.07,
    color: color.primaryText,
  },
  btnView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 25,
    justifyContent: 'space-between',
    padding: 10,
    marginHorizontal: 28,
    // marginBottom: 18,
  },
  btnContainer: {
    width: 114,
    backgroundColor: color.lightgray,
    height: 39,
    borderRadius: 10,
    marginTop: 0,
    paddingTop: 0,
  },
  btnEditModalContainer: {
    width: 114,
    backgroundColor: color.primary,
    height: 39,
    borderRadius: 10,
    marginTop: 0,
    paddingTop: 0,
  },
  btnCancelContainer: {
    width: 114,
    backgroundColor: color.warning,
    height: 39,
    borderRadius: 10,
    marginTop: 0,
    paddingTop: 0,
  },
  nameTextStyle: {
    fontSize: 14,
    color: color.secondaryBG,
    lineHeight: 19,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
  },
  nameTextButtonCancelStyle: {
    fontSize: 14,
    color: color.primaryText,
    lineHeight: 19,
    fontFamily: font.openSansRegular,
    fontWeight: '600',
  },
});

export default styles;
